# Generated by Django 6.0.2 on 2026-02-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_doctor_phone_remove_doctor_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
