# Generated by Django 6.0.2 on 2026-03-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_date_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
