# Generated by Django 6.0.2 on 2026-04-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_doctor_certificate_doctor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_token_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_token_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
