# Generated by Django 6.0.2 on 2026-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_medicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_type',
            field=models.CharField(choices=[('Prescription', 'Prescription'), ('Lab Report', 'Lab Report'), ('Scan', 'Scan'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
