# Generated by Django 6.0.2 on 2026-04-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency')], default='Normal', max_length=20),
        ),
    ]
